### ISSUE TITLE
[Suggestion] Toggle playerEntity source

### ISSUE THREAD

**Issue by AnikeiPS** [tr7zw/PaperDoll#24]
Allow toggle between `mc_instance.getCameraEntity()` and `mc_instance.player` playerEntity source.

**Comment by tr7zw** [comment]
That should already be the case? When you spectate another player or mob it should show then instead?

**Comment by AnikeiPS** [comment]
I mean in config. Should mod always use mc_instance.player or use only if camera entity is null.

**Comment by AnikeiPS** [comment]
I have problems with [Freecam mod](https://modrinth.com/mod/freecam): when I turn freecam on, paper doll display swimming Alex.

**Comment by tr7zw** [comment]
That's because the freecam mod replaces the camera entity with some dummy, so it works as intended. Otherwise, it would show weird stuff when spectating etc. If anything it should hide the paperdoll while in freecam mode. The issue with that is, that there are like 3+ freecam mods, which makes it a pain to support.

**Comment by AnikeiPS** [comment]
Yeah, I know, but is there a way to fix it?

**Comment by tr7zw** [comment]
Adding special logic for each and every free cam mod on forge and fabric, which is a pain in the ass. That's why its not part of the mod. At least not high on my priority list.

**Comment by AnikeiPS** [comment]
I'll try fixing this issue on my end. Thanks!
